version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "443:443"
    depends_on:
      - webapi
  webapi:
    build:
      context: ./ebooking-api
      dockerfile: Dockerfile
    ports:
      - "80"
    environment:
      DB_SERVER: db
      DB_NAME: 170171
      DB_USER: sa
      DB_PASSWORD: Lekovitobilje22!
      JWT_KEY: aaaaaaaaaaaaaaaaasssssssssssssssssssssssswwwwwwwwwwwwwwwwwwwwwwww
      JWT_ISSUER: localhost
      JWT_AUDIENCE: localhost
    depends_on:
      - db


  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   restart: unless-stopped
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=user
  #     - RABBITMQ_DEFAULT_PASS=mypass
  #   ports:
  #     - "5672:5672"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Lekovitobilje22!"
    ports:
      - "7777:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: