version: '3.8'
services:

  webapi:
    build:
      context: ./ebooking-api
      dockerfile: Dockerfile-API
    env_file:
      - .env
    ports:
      - 9999:80
    depends_on:
      - db
      - rabbitmq

  messenger:
    build:
      context: ./ebooking-api
      dockerfile: Dockerfile-Messenger
    env_file:
      - .env
    ports:
      - 8888:80
    depends_on:
      - db
      - webapi
      - rabbitmq
  
  paymentapp:
    build:
      context: ./ebooking-api
      dockerfile: Dockerfile-PaymentApp
    env_file:
      - .env
    ports:
      - 6666:80
    depends_on:
      - db
      - webapi
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672

  db:
    build:
      context: ./database
      dockerfile: Dockerfile-Database
    ports:
      - "7777:1433"
volumes:
  mssql_data:

